"""add location to events

Revision ID: 721ec7b29e0c
Revises: bc3f8334b286
Create Date: 2026-08-18 15:39:06.043276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '721ec7b29e0c'
down_revision: Union[str, Sequence[str], None] = 'bc3f8334b286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('location', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'location')
    # ### end Alembic commands ###
