"""add latitude longitude to events

Revision ID: a5a886340c29
Revises: 721ec7b29e0c
Create Date: 2026-08-19 02:24:31.739087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a886340c29'
down_revision: Union[str, Sequence[str], None] = '721ec7b29e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'longitude')
    op.drop_column('events', 'latitude')
    # ### end Alembic commands ###
